spring:
  datasource:
    url: jdbc:mysql:///cnadmin?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: Kuku1433
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  redis:
    host: localhost
    password:

